```plantuml
left to right direction
skinparam linetype polyline

node "Input" as input {
    node "Training data" as traindata
    node "Test data" as testdata
    node "Annotations" as anno {
        node "Sensitive variables\n(e.g. patient gender)" as sens
    }
    node "Model" as model
}

node "Overfit exploration plugin" as overfit {
    node "UMAP" as umap
    node "sensitive variable fine-tuning" as finetune {
        label "<img:MONAI-logo-color.png{scale=.3}>" as monai
        label "<img:Pytorch_logo.png{scale=.2}>" as pytorch
    }
    node "fairness measuring" as fairness {
        /'
        This node is different from others in the sense
        that it relies on having a downstream task
        '/
    }
}

node "Output" {
    node "plot" as plot
    node "plot scores" as plotscores
    node "fairness score" as score
    node "fine-tuning accuracy" as accuracy
}

input ---> overfit
fairness --> score
finetune --> accuracy
umap --> plot
umap --> plotscores
```
