```plantuml
left to right direction
skinparam linetype polyline

node "Input" as developer {
    node "Training data" as train
    node "Annotations" as anno {
        node Labels as labels
        node "Sensitive variables\n(such as patient\ngender, age, etc)" as sens
    }
}

/'
node <img:MONAI-logo-color.png> as monai {
    node "Imageloader" as imageloader
    node "<img:Pytorch_logo.png{scale=.2}>" as pytorch
    node "Distributed trainer\n\t<img:distributed.png{scale=.10}>"
}
'/
/'
I should use WSIs as the input, not just "Training data"
'/

node "Model SSL training" as trainer {
    hexagon "Conditional Sampler" as sampler
    node "training" as training {
        label "<img:MONAI-logo-color.png{scale=.3}>" as monai
        label "<img:Pytorch_logo.png{scale=.2}>" as pytorch
    }
}

node "Output"  as output {
    node "Model" as model
}

/'
monai -left[hidden]-> developer
monai -left[hidden]-> trainer
monai -down[hidden]-> overfit
monai -down[hidden]-> analysis
monai .d. trainer
monai .. overfit
'/
train --> "training"
sampler --> training
sens --> sampler
trainer ---> output
```